routes/web.php
<?php

use multiventas\Models\Categoria;
use multiventas\Models\Cliente;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('auth/login');


});

Route::get('/listaCategorias/{documento}', function ($documento) {
    $lista = Cliente::where('documento',$documento)->first();  
   // return $lista;
return $lista;

});
Route::get('/archivo', function () {
    $pdf = PDF::loadView('factura');
    return $pdf->download('factura.pdf');
  });
  

Route::get('/listaCaServicios/{servicio_id}', function ($servicio_id) {
        $categoria = Categoria::where('categoria_id',$servicio_id)->get(); 

        return $categoria;
    });
    Route::get('/listaprecio/{id}', function ($id_categorias) {
        $precio = Categoria::where('id',$id_categorias)->first(); 
        return $precio;

    });



Route::group(['middleware' => 'auth'], function() {
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('clientes', 'ClientesController');
    Route::resource('empleados', 'EmpleadosController');
    Route::resource('productos', 'ProductosController');
    Route::resource('usuarios', 'UsuariosController');
    Route::resource('manos', 'ManosController');
    Route::resource('pies', 'PiesController');
    Route::resource('colores', 'ColoresController');
    Route::resource('CrearCita', 'CitasController');
    Route::resource('keratinas', 'KeratinasController');
    Route::resource('maquillajes', 'MaquillajesController');
    Route::resource('peinados', 'PeinadosController');
    Route::resource('promociones', 'PromocionesController');
    Route::resource('cortes', 'CortesController');
    Route::resource('depilaciones', 'DepilacionesController');
    Route::resource('facturaciones', 'FacturacionsController');
    Route::resource('categoria', 'CategoriaController');

   // Mail::to($users)->send(new EmailConfirmation($users));
    Route::get('events', 'EventsController@index');
    Route::get('opciones', function () {
        return view('admin.Agenda.agendar');     

    });
    Route::get('servicios', function () {
        return view('admin.servicio.Servicios');
      

    });
});
    /*Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
        Route::resource('login', 'LoginController');
              
    
        });*/
        
   
});



Route::get('/home', 'HomeController@index')->name('home');



Route::get('/home', 'HomeController@index')->name('home');



Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'Auth', 'namespace' => 'Auth'], function () {

   
Route::get('password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.reset');
Route::post('password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}','ForgotPasswordController@showResetForm')->name('password.reset.token');
Route::post('password/reset','ResetPasswordController@reset');
});
Auth::routes();

app/Models/Categoria.php
<?php

namespace multiventas\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Categoria extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'nombre',
        'precio',
        'categoria_id',
    ];

    /**
     * Get the brand that the product belongs to.
     */
    public function brand()
    {
        return $this->belongsTo('multiventas\Models\Marca','brand_id');
    }

    /**
     * Get the category that the product belongs to.
     */
    public function category()
    {
        return $this->belongsTo('multiventas\Models\Categoria','category_id');
    }
}

app/Http/Controllers/Admin/CategoriaController.php
<?php

namespace multiventas\Http\Controllers\Admin;

use Illuminate\Http\Request;
use multiventas\Http\Controllers\Controller;
use multiventas\Models\Facturacion;
use multiventas\Models\Categoria;
use multiventas\Models\Servicio;
use multiventas\Models\Cliente;
use multiventas\Models\Producto;
use Illuminate\Support\Facades\Redirect;
use multiventas\Http\Requests\CategoriaFormRequest;
use DB;


class CategoriaController extends Controller
{
    public function __construct()
    {

    }
    public function index()
    {
        $categorias = Facturacion::all();
          $lista= Cliente::all() ;
          $servicios=Servicio::all();
          $producto=Producto::all();
          $numero_factura = Facturacion::all()->max();
          $categoria=Categoria::all();
          $suma=0;
          $listaProductos = Producto::all()->where('factura',$numero_factura->id);  

              return view('admin.categoria.index',["categorias"=>$categorias,"lista"=>$lista,"servicios"=>$servicios,
              "categoria"=>$categoria,"producto"=>$producto,"numero_factura"=>$numero_factura,"listaProductos"=>$listaProductos,"suma"=>$suma]);
        }
    
    public function store(Request $request)
    {
        $producto=new Producto;
        $producto->categoria=$request->get('servicios');
        $producto->servicio=$request->get('categorias');
        $producto->precio_unidad=$request->get('precio');
        $producto->cantidad=$request->get('cantidad');
        $producto->total_sin_iva=$request->get('resultado');
        $producto->iva=$request->get('iva');
        $producto->total=$request->get('totalIva');
        $producto->factura=$request->get('facturas')-1;
        $producto->save();
        return Redirect::to('admin/categoria');

    }
    public function numero_factura($id)
    {
                $categoria = Facturacion::all()->max();
              
                   
        }
        function mostrarservicios() {
           
         }
        
    public function edit($id)
    {
        return view("admin.categoria.edit",["categoria"=>Categoria::findOrFail($id)]);
    }
    public function update(CategoriaFormRequest $request,$id)
    {
        $categoria=Categoria::findOrFail($id);
        $categoria->nombre=$request->get('nombre');
        $categoria->descripcion=$request->get('descripcion');
        $categoria->update();
        return Redirect::to('admin/categoria');
    }
    public function destroy($id)
    {
        $categoria=categoria::findOrFail($id);
        $categoria->condicion='1';
        $categoria->update();
        return Redirect::to('admin/categoria');
    }
    
}

resources/views/admin/categoria/create.blade.php
@extends ('layouts.admin')
@section ('contenido')
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
			<h3>Nueva Categoría</h3>
			@if (count($errors)>0)
			<div class="alert alert-danger">
				<ul>
				@foreach ($errors->all() as $error)
					<li>{{$error}}</li>
				@endforeach
				</ul>
			</div>
			@endif

			{!!Form::open(array('url'=>'almacen/categoria','method'=>'POST','autocomplete'=>'off'))!!}
            {{Form::token()}}
            <div class="form-group">
            	<label for="nombre">Nombre</label>
            	<input type="text" name="nombre" class="form-control" placeholder="Nombre...">
            </div>
            <div class="form-group">
            	<label for="descripcion">Descripción</label>
            	<input type="text" name="descripcion" class="form-control" placeholder="Descripción...">
            </div>
            <div class="form-group">
            	<button class="btn btn-primary" type="submit">Guardar</button>
            	<button class="btn btn-danger" type="reset">Cancelar</button>
            </div>

			{!!Form::close()!!}		
            
		</div>
	</div>
@endsection

resources/views/admin/categoria/edit.blade.php
@extends ('layouts.admin')
@section ('contenido')
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
			<h3>Editar Categoría: {{ $categoria->nombre}}</h3>
			@if (count($errors)>0)
			<div class="alert alert-danger">
				<ul>
				@foreach ($errors->all() as $error)
					<li>{{$error}}</li>
				@endforeach
				</ul>
			</div>
			@endif

			{!!Form::model($categoria,['method'=>'PATCH','route'=>['almacen.categoria.update',$categoria->idcategoria]])!!}
            {{Form::token()}}
            <div class="form-group">
            	<label for="nombre">Nombre</label>
            	<input type="text" name="nombre" class="form-control" value="{{$categoria->nombre}}" placeholder="Nombre...">
            </div>
            <div class="form-group">
            	<label for="descripcion">Descripción</label>
            	<input type="text" name="descripcion" class="form-control" value="{{$categoria->descripcion}}" placeholder="Descripción...">
            </div>
            <div class="form-group">
            	<button class="btn btn-primary" type="submit">Guardar</button>
            	<button class="btn btn-danger" type="reset">Cancelar</button>
            </div>

			{!!Form::close()!!}		
            
		</div>
	</div>
@endsection

resources/views/admin/categoria/index.blade.php
@extends ('layouts.administracion_categoria')

@extends('layout')
@section ('contenido')
<!DOCTYPE html>
<html>
<head>
	
</head>
<body>
	<div class="row">
		
				<div class="container text-center"   >
				<div class="col-sm-3">
				<h4><dt>  Fecha: <?=date('m/d/Y');?></dt></h4>
			</div>
				<div class="col-sm-3">
					<h4><dt>Nit: xxxxxxx  </dt></h3>
					</div>
						<div class="col-sm-3">	
					<h4><dt>Empresa: Liz Salon  </dt> </dt></h3>	
				</div>
			</div>
			<div class="row">
					<div class="container text-center"   >
				<div class="col-sm-6">
					<label for="sel2">Documento Cliente:</label>
					 <select  id="select2" >
						 	<option>seleccione documento </option>
						  @foreach($lista as $cat)						  				
						    <option value="{{$cat->documento}}">{{$cat->documento}}</option>																
							@endforeach
							</select>
				</div>
				<div class="col-sm-6">
								<label  for="nombres">Nombre cliente :   </label>
								<label  id="nombre" name='nombres'></label>
								<label  id="apellido"></label>
				</div>
			</div>
		          <form method="post" action="{{ route('categoria.store') }}" data-parsley-validate ><class="form-horizontal form-label-left">
		          	{{ csrf_field() }}
			<div class="row">
					<div class="container text-center"   >
							<div class="col-sm-6">
									<label for="sel1">Categoria:</label>
							  <select  id="servicios" name="servicios">
									<option value=""> seleccione categoria</option>										  

									@foreach ($servicios as $cat)					
							<option value="{{$cat->id}}">
										 {{$cat->nombre}}</option>
											 @endforeach
									</select>
			</div>
							<label for="sel1">Servicios:</label>
								<select  id="categorias" name="categorias">									 					
							 	<option value=""> seleccione servicio </option>										  
									</select>
								</div>
					</div>
			</div>
			<div class="row">
			<div class="container text-center"   >

				<div class="col-sm-6">
					<label  for="nombres">Precio :   </label>
					<input  id="precio" name="precio" readonly="readonly"></input>
				</div>
				<label  for="nombres">cantidad :   </label>
				<input  id="cantidad" name="cantidad" ></input>
				<input  type="hidden" id "numero_factura" name="facturas" for="facturas" value="{{$numero_factura->id+1}}"  ></input>
				<button type="button" onclick="calcularResultado()">calcular Precio</button>
			</div>
	<div class="row">
		<div class="container text-center"   >
<label  for="nombrecantidad">cantidad total sin iva:   </label>
	<input  id="resultado" name="resultado"readonly="readonly"></input>
	<label  for="nombrecantidad2">Iva:   </label>
	<input  id="iva" name="iva" readonly="readonly"></input>
	<label  for="nombrecantidad3">cantidad total con iva:   </label>
	<input  id="totalIva" name="totalIva" readonly="readonly"></input>

</div>
</div>
<div class="container text-center"  > 

<button type="submit" class="btn btn-success">Agregar producto</button>
</div>
		</div>
			</div>
			</div>
			</div>
		</form>
<h3>Listado de Servicios </h3>
<div class="row">
		<div class="container text-center"   >
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-condensed table-hover">
				<thead>
					<th>categoria</th>
					<th>servicio</th>
					<th>Precio Unidad</th>
					<th>Cantidad</th>
					<th>Total Sin Iva</th>
					<th>Iva</th>
					<th>Total</th>
					@if (count($listaProductos))
					@foreach ($listaProductos as $cat)
				</thead>
				<tr>
					<td>{{ $cat->categoria}}</td>
					<td>{{ $cat->servicio}}</td>
					<td>{{ $cat->precio_unidad}}</td>
					<td>{{ $cat->cantidad}}</td>
					<td>{{ $cat->total_sin_iva}}</td>
					<td>{{ $cat->iva}}</td>
					<td>{{ $cat->total}}</td>

				</tr>
				@endforeach
				@endif
				</tr>
							
			</table>
			<table class="table table-striped table-bordered table-condensed table-hover">
				<thead>
					@if (count($listaProductos))
					@foreach ($listaProductos as $cat)
			{{ $suma+=$cat->total}}
				</thead>
			    @endforeach
				@endif
					<th>Total</th>
					
			<th>{{ $suma}}</th>
				</tr>
							
			</table>
			<form method="post" action="{{ route('facturaciones.store') }}" data-parsley-validate ><class="form-horizontal form-label-left">
				{{ csrf_field() }}

				<button type="submit" class="btn btn-success">Nueva Factura</button>
		</div>
	</div>
</div>

</div>
<script type="text/javascript" src="{{asset('js/jQuery-2.1.4.min.js')}}"></script>
<script>
	$('#select2').change(function(){
		console.log($(this).val())
		$.get('/listaCategorias/'+$(this).val()).done(function(lista){
			$('#nombre').val(lista.nombre)
			console.log(lista.nombre)
			$('#apellido').val(lista.apellido)

		});
	});
	
	</script>
	<script type="text/javascript">
		$('#categorias').change(function(){
			console.log($(this).val())
			$.get('/listaprecio/'+$(this).val()).done(function(precio){
				$('#precio').val(precio.precio)
	
			});
		});
		
		</script>
		
		<script>
		function calcularResultado(){
			var cantidadProducto = $("#cantidad").val();
			var precio = $("#precio").val();
			var multiplicacion = cantidadProducto * precio;
			var iva=multiplicacion*0.19;
			var totalSinIva=multiplicacion-iva;
			
			$('#resultado').val(totalSinIva);
			$('#iva').val(iva);
			$('#totalIva').val(multiplicacion);
		}
	</script>
		
	<script type="text/javascript">
	$('#servicios').change(function(){
		console.log($(this).val())
		$.get('/listaCaServicios/'+$(this).val()).done(function(categorias){
			$('#categorias').html('')
			$('#categorias').append('<option value=""> seleccione servicio </option>')
			$.each(categorias,function(idnex,categoria){
				$('#categorias').append('<option value="'+categoria.id+'">'+categoria.nombre+'</option>');
			})
		})
	});
</script>

</body>
</html>
@endsection

resources/views/admin/categoria/modal.blade.php
<div class="modal fade modal-slide-in-right" aria-hidden="true"
role="dialog" tabindex="-1" id="modal-delete-{{$cat->idcategoria}}">
	{{Form::Open(array('action'=>array('CategoriaController@destroy',$cat->idcategoria),'method'=>'delete'))}}
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
				aria-label="Close">
                     <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Eliminar Categoría</h4>
			</div>
			<div class="modal-body">
				<p>Confirme si desea Eliminar la categoría</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary">Confirmar</button>
			</div>
		</div>
	</div>
	{{Form::Close()}}

</div>

resources/views/admin/categoria/search.blade.php
{!! Form::open(array('url'=>'admin/categoria','method'=>'GET','autocomplete'=>'off','role'=>'search')) !!}
<div class="form-group">
	<div class="input-group">
		<input type="text" class="form-control" name="searchText" placeholder="Buscar..." value="{{$searchText}}">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-primary">Buscar</button>
		</span>
	</div>
</div>

{{Form::close()}}